config/routes.rb
Rails.application.routes.draw do
  root "schedules#index"
  get '/new', to: "schedules#new"
  get '/index', to: "schedules#index"
  get "/edit", to: "schedules#edit"

  post "/new", to: "schedules#create"
  
  resources :schedules
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  validates :title, presence: true, length: {in: 1..20}
  validates :start_day, presence: true
  validates :end_day, presence: true
  validate :validate_date_end_day_after_start_day
  validates :memo, length: {minimum:0, maximum:500}

  def validate_date_end_day_after_start_day
    if start_day.present? && end_day.present?
      if Time.parse(end_day.to_s).to_i < Time.parse(start_day.to_s).to_i
        errors.add(:end_day,"は開始日以降の日付を指定してください")
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schedule_controller.rb
class ScheduleController < ApplicationController
  def create
  end

  def read
  end

  def update
  end

  def delete
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(schedule_params)
    if @schedule.save
      flash.now[:info] = "スケジュールが作成されました"
      redirect_to :index
    else
      flash.now[:warning] = "入力内容に問題があります！"
      render "new"
    end
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(schedule_params)
      flash.now[:info] = "スケジュールが更新されました"
      redirect_to :index
    else
      flash.now[:warning] = "入力内容に問題があります！"
      render "edit"
    end
  end

  def index
    @schedules = Schedule.all
  end

  def destroy_page
    @schedule = Schedule.find(params[:id])
  end

  def destroy
    Schedule.find(params[:id]).destroy
    flash.now[:success] = "スケジュールが削除されました"
    redirect_to :index
  end

  def show
    @schedule = Schedule.find(params[:id])
  end

  private
    def schedule_params
      params.require(:schedule).permit(:title, :start_day, :end_day, :all_day, :memo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedule_helper.rb
module ScheduleHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/app/new.html.erb
<% provide(:title, "スケジュール登録") %>
<h3>スケジュール登録</h3>

<%= form_with(model: @app) do |f| %>
  <table>
    <tr>
      <th><%= f.label :title , "予定名" %></th>
      <td><%= f.text_field :title, class: "form-control" %></td>
    </tr>

    <tr>
      <th><%= f.label :start_day, "開始日" %></th>
      <td><%= f.date_field :start_day, class: "form-control"  %></td>
    </tr>

    <tr>
      <th><%= f.label :end_day, "終了日" %></th>
      <td><%= f.date_field :end_day, class: "form-control"  %></td>
    </tr>

    <tr>
      <th><%= f.label :all_day, "終日予定" %></th>
      <td><%= f.radio_button :all_day, "終日", class: "form-control"  %></td>
    </tr>

    <tr>
      <th><%= f.label :memo, "メモ" %></th>
      <td><%= f.text_area :memo, class: "form-control"  %></td>
    </tr>
  </table>

  <div>
    <ul>
      <li><%= f.submit "登録",  class: "btn btn-primary" %></li>
      <li><%= link_to "一覧へ", "index" %></li>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header>
    <ul class="nav justify-content-end">
        <li class="nav-item navbar-text">今日は<%= Time.now.strftime("%Y年%m月%d日") %></li>
        <li class="nav-item"><%= link_to "一覧", "/index", class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "新規登録", "/new", class: "nav-link" %></li>
    </ul>  
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title><%= yield(:title) || "スケジュールアプリ" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>

  <body>
    <!--header-->
    <%= render "layouts/header" %>
    <% flash.each do |message_type,message| %>
      <div class="alert alert-<%= message_type%>">
        <%= message %>
          <% if @schedule.present? %>
            <% if @schedule.errors.any? %>
              <div class="alert">
                <ul>
                  <% @schedule.errors.full_messages.each do |errormessage| %>
                    <li><%= errormessage %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
          <% end %>
      </div>
    <% end %>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

app/views/schedule/create.html.erb
<h1>Schedule#create</h1>
<p>Find me in app/views/schedule/create.html.erb</p>

app/views/schedule/delete.html.erb
<h1>Schedule#delete</h1>
<p>Find me in app/views/schedule/delete.html.erb</p>

app/views/schedule/read.html.erb
<h1>Schedule#read</h1>
<p>Find me in app/views/schedule/read.html.erb</p>

app/views/schedule/update.html.erb
<h1>Schedule#update</h1>
<p>Find me in app/views/schedule/update.html.erb</p>

app/views/schedules/_schedule_form.html.erb
<%= form_with model: @schedule do |f| %>
  <table class="col-md-6 text-center form-base">
    <tr>
      <th><%= f.label :title , "予定名" %></th>
      <td><%= f.text_field :title, class: "form-control" %></td>
    </tr>

    <tr>
      <th><%= f.label :start_day, "開始日" %></th>
      <td><%= f.date_field :start_day, class: "form-control"  %></td>
    </tr>

    <tr>
      <th><%= f.label :end_day, "終了日" %></th>
      <td><%= f.date_field :end_day, class: "form-control"  %></td>
    </tr>

    <tr>
      <th><%= f.label :all_day, "終日予定" %></th>
      <td><%= f.check_box :all_day, class: "form-control"  %></td>
    </tr>

    <tr>
      <th><%= f.label :memo, "メモ" %></th>
      <td><%= f.text_area :memo, class: "form-control"  %></td>
    </tr>
  </table>

  <div class="submit-btn">
      <%= f.submit yield(:button_text),  class: "btn btn-primary" %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<% provide(:title, "スケジュール更新") %>
<% provide(:button_text, "更新") %>

<div class="container">
  <h3>スケジュール更新</h3>
  <%= render "schedule_form" %>

  <%= link_to "一覧へ", "/index", class: "btn btn-primary" %>
</div>

app/views/schedules/index.html.erb
<div class="container-xl">
  <h3>スケジュール一覧</h3>
  <table>
    <thead>
      <tr class="index-col text-center">
        <th>登録番号</th>
        <th>タイトル</th>
        <th>開始日</th>
        <th>終了日</th>
        <th>終日設定</th>
        <th>更新日</th>
        <th>操作</th>
      </tr>
    </thead>
    <br>
    <tbody class="index-col">
      <p>スケジュールは合計 <%= @schedules.count %>件あります</p>
      <% @schedules.each do |schedule| %>
        <tr>
          <td class="text-center"><%= schedule.id %></td>
          <td class="text-center"><%= schedule.title %></td>
          <td><%= schedule.start_day.strftime("%Y/%m/%d") %></td>
          <td><%= schedule.end_day.strftime("%Y/%m/%d") %></td>
          <td class="text-center"> 
            <% if schedule.all_day %>
              ⚪︎
            <% end %>
          </td>
          <td><%= schedule.updated_at.strftime("%Y年%m月%d日 %H時%M分") %></td>
          <td>
            <%= link_to "詳細確認", schedule_path(schedule), class: "btn btn-primary" %>
            <%= link_to "編集", edit_schedule_path(schedule), class: "btn btn-primary" %>
            <%= link_to "削除", schedule_path(schedule) , method: :delete, data: { confirm: "削除しますか？" }, class: "btn btn-primary" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/schedules/new.html.erb
<% provide(:title, "スケジュール登録") %>
<% provide(:button_text, "作成") %>

<div class="container">
  <h3>スケジュール登録</h3>
  <%= render "schedule_form" %>

  <%= link_to "一覧へ", "/index", class: "btn btn-primary" %>
</div>

app/views/schedules/show.html.erb
<% provide(:title, "スケジュール詳細") %>
<h3>スケジュール確認</h3>

  <table class="col-md-6 text-center show-base">
  <tr>
    <th>予定名</th>
    <td><%= @schedule.title %></td>
  </tr>
  <tr>
    <th>開始日</th>
    <td><%= @schedule.start_day.strftime("%Y/%m/%d") %></td>
  </tr>
  <tr>
    <th>終了日</th>
    <td><%= @schedule.end_day.strftime("%Y/%m/%d") %></td>
  </tr>
  <tr>
    <th>終日か</th>
    <td>
      <% if @schedule.all_day %>
        ⚪︎
      <% end %>
    </td>
  </tr>
  <tr>
    <th>詳細内容</th>
    <td><%= @schedule.memo %></td>
  </tr>
</table>
<%= link_to "編集", edit_schedule_path(@schedule), class: "btn btn-primary"%>
<%= link_to "一覧へ", "/index" , class: "btn btn-primary"%>